### ISSUE TITLE
When using multiple ACs - no need to refresh SID for each AC independently

### ISSUE THREAD

**Issue by GuyKh** [yonatanp/electrasmart-custom-component#10]
This probably relates to the `electrasmart` project structure rather than HomeAssistant component structrue.

I'm using 4 ACs in the same component - and my log (in debug) is filled with `renewed sid` messages.

I think that the structure should be changed so that `renewSid` or `validateToken` would happen on the component level (once) and not on the AC level

**Comment by yonatanp** [comment]
I agree. And in fact, it _is_ the ClimateEntity that decides when to trigger a renewal. The problem is that with 4 AC units, you get 4 ClimateEntity instances that don't talk to each other. We can solve this by creating a shared renewal timer that they all share between them.

**Comment by yonatanp** [comment]
I will build and publish a new `electrasmart` version including your shared sir changes, and then we can modify the component to take advantage of that.

**Comment by GuyKh** [comment]
Added that capability. #15
