### ISSUE TITLE
No 'version' key in the manifest file for custom integration 'electrasmart'.

### ISSUE THREAD

**Issue by GuyKh** [yonatanp/electrasmart-custom-component#17]
From HomeAssistant 2021.3.0:
```
No 'version' key in the manifest file for custom integration 'electrasmart'. This will not be allowed in a future version of Home Assistant. Please report this to the maintainer of 'electra
smart'
```

Relevant docs:
https://developers.home-assistant.io/docs/creating_integration_manifest/#version

**Comment by moshco** [comment]
hi,
any update when it will be fix? for now, integration doesn't work at all, because it not loaded.

**Comment by yonatanp** [comment]
@moshco I've added the relevant field. Could you please confirm that it's fixed, so I can close the ticket? thanks!

**Comment by moshco** [comment]
Still,dosen't working. I'm getting this messahe:

<Integration yonatanp/electrasmart-custom-component> Could not read manifest.json [Expecting ',' delimiter: line 8 column 20 (char 251)]

**Comment by yonatanp** [comment]
Yes, my apologies, I had a typo there. It should work now.
Could you try again?

**Comment by moshco** [comment]
well done. good job!
thanks
