### ISSUE TITLE
Off and temp Commands are not sent to the AC Unit

### ISSUE THREAD

**Issue by odedgil** [yonatanp/electrasmart-custom-component#5]
it seems like the current status is being updated from the unit but the send_command is not working.
as per the following log, you can see the temp was set to 23 but AC returns 22.
I have Electra Magic 370

020-10-18 13:31:28 DEBUG (SyncWorker_50) [custom_components.electrasmart.climate] setting new temperature to 23.0
2020-10-18 13:31:28 DEBUG (SyncWorker_50) [custom_components.electrasmart.climate] renewing sid
2020-10-18 13:31:30 DEBUG (SyncWorker_50) [custom_components.electrasmart.climate] new temperature was set to 23.0
2020-10-18 13:31:31 DEBUG (SyncWorker_0) [custom_components.electrasmart.climate] Updating status using the client AC instance...
2020-10-18 13:31:31 DEBUG (SyncWorker_0) [custom_components.electrasmart.climate] Status updated using the client AC instance
2020-10-18 13:31:31 DEBUG (MainThread) [custom_components.electrasmart.climate] value of hvac_mode property: cool (derived from COOL)
2020-10-18 13:31:31 DEBUG (MainThread) [custom_components.electrasmart.climate] value of current_temperature property: 23
2020-10-18 13:31:31 DEBUG (MainThread) [custom_components.electrasmart.climate] value of target_temperature property: 22
2020-10-18 13:31:31 DEBUG (MainThread) [custom_components.electrasmart.climate] value of fan_mode property: auto (derived from AUTO)
2020-10-18 13:31:38 DEBUG (SyncWorker_1) [custom_components.electrasmart.climate] Updating status using the client AC instance...
2020-10-18 13:31:38 DEBUG (SyncWorker_1) [custom_components.electrasmart.climate] Status updated using the client AC instance
2020-10-18 13:31:38 DEBUG (MainThread) [custom_components.electrasmart.climate] value of hvac_mode property: cool (derived from COOL)
2020-10-18 13:31:38 DEBUG (MainThread) [custom_components.electrasmart.climate] value of current_temperature property: 23
2020-10-18 13:31:38 DEBUG (MainThread) [custom_components.electrasmart.climate] value of target_temperature property: 22
2020-10-18 13:31:38 DEBUG (MainThread) [custom_components.electrasmart.climate] value of fan_mode property: auto (derived from AUTO)

i can't write python code but from your code I could generate the http post call (via postman) as try to send the commands to the AC. 
i didn't succeed sending the commands as well using:

POST /mobile/mobilecommand HTTP/1.1
Host: app.ecpiot.co.il
Content-Type: application/json
Cookie: GCLB=CLv_vc7k9Ju9Zw

{ "pvdid":"1","id":"999","sid":"xxxxxxxxxxxxxxxx","cmd":"SEND_COMMAND","data":{"id":"xxxxxxxxx","commandJson": { "OPER":{
    "OPER": {
        "MSGTYPE":"OPER",
        "IDU_PN":"",
        "AC_MODE": "AFF",
        "FANSPD": "AUTO",
        "SPT": 22,
        "TIMER": "OFF",
        "SHABAT": "OFF",
        "IFEEL": "OFF",
        "SLEEP": "OFF",
        "CLEAR_FILT": "OFF",
        "AC_STSRC": "WI-FI",
        "DIAG_L2_PRD": "3600",
        "FW_OTA": "None"
    }
}}}}

maybe if you help me with my http post command i'll be able to help you with this issues.
thanks!

**Comment by odedgil** [comment]
Can anyone help with this issue?
HA is displaying the updated state, after I send the command the AC beeps, but nothing happens.
Can you please provide a valid POST request so I can test with my AC unit via postman first?

**Comment by yonatanp** [comment]
Hi @odedgil, sorry for the delayed response.
We have fixed some major issues over the last couple of days.
Please upgrade the component to the latest version, and check to see if your issue is resolved.

If it isn't, please enable debug logging for both the component and the underlying library (see details in the README) and you will see in the log the details of the POST command being sent, as well as the returned result.

You're welcome to share the post and the followup status here. It will help us debug the issue further. As always, take care not to post authorization secrets (imei, token or sid).

**Comment by odedgil** [comment]
Thank you for the hard work 👍 
with the new version everything works except turning off the AC.
I can see that when you turn off the AC you send (for example):
 {"cmd": "SEND_COMMAND",
 "data": { "commandJson": '{"OPER": {"MSGTYPE": "OPER", "IDU_PN": "","AC_MODE": "STBY", "FANSPD": "AUTO", "SPT": "23","TIMER": "OFF", "HSWING": "ON", "VSWING": "OFF","TURN_ON_OFF": "OFF", "SLEEP": "OFF", "SHABAT":"OFF", "CLEAR_FILT": "OFF", "OP_VAL_ERR": "OK","TURBO": "OFF", "IFEEL":"OFF" }}', "id": "yyyyyy"},"id": jjjjj, "pvdid": 1, "sid" : "xxxxxxxxxxxxxxxx"}

this post message doesn't turn off my AC,  i seems like STBY is not a valid mode so the command is being ignored.
if I change the "AC_MODE": "STBY" to "AC_MODE": "COOL" and only keep the  "TURN_ON_OFF": "OFF" the AC will turn off.

it seems like some commands are not being sent to the server at all, i changed the temp to 21 and there is no command being sent to actually change the temp:

2020-10-27 01:44:18 DEBUG (SyncWorker_29) [custom_components.electrasmart.climate] Status updated using the client AC instance
2020-10-27 01:44:18 DEBUG (SyncWorker_29) [custom_components.electrasmart.climate] new temperature was set to 21.0
2020-10-27 01:44:18 DEBUG (SyncWorker_33) [custom_components.electrasmart.climate] Updating status using the client AC instance...
2020-10-27 01:44:18 DEBUG (SyncWorker_33) [electrasmart.client] Posting request
id: 1209
url: https://app.ecpiot.co.il/mobile/mobilecommand
headers: {'user-agent': 'Electra Client'}
post json data:
{'cmd': 'GET_LAST_TELEMETRY',
 'data': {'commandName': 'OPER,DIAG_L2,HB', 'id': 'ttttttt'},
 'id': 1209,
 'pvdid': 1,
 'sid': 'xxxxxxxxxxxxxxxxxxxxxxxxx'}
2020-10-27 01:44:18 DEBUG (SyncWorker_33) [electrasmart.client] Response received (id=1209):
{'data': {'commandJson': {'DIAG_L2': '{"DIAG_L2" : {"MSGTYPE" : '
                                     '"DIAG_L2","IDU_PN" : "","O_ODU_MODE" : '
                                     '"COOL","I_RAT" : "23","O_OAT" : '
                                     '"","IDU_FAN" : "AUTO"}}',
                          'HB': None,
                          'OPER': '{"OPER" : {"MSGTYPE" : "OPER","IDU_PN" : '
                                  '"","AC_MODE" : "COOL","FANSPD" : '
                                  '"AUTO","SPT" : "23","TIMER" : '
                                  '"OFF","HSWING" : "ON","VSWING" : '
                                  '"OFF","TURN_ON_OFF" : "ON","SLEEP" : '
                                  '"OFF","SHABAT" : "OFF","CLEAR_FILT" : '
                                  '"OFF","OP_VAL_ERR" : "OK","TURBO" : '
                                  '"OFF","IFEEL" : "OFF"}}'},
          'res': 0,
          'res_desc': None,
          'timeDelta': 7},
 'desc': None,
 'id': jjjjj,
 'status': 0}
2020-10-27 01:44:18 DEBUG (SyncWorker_33) [custom_components.electrasmart.climate] Status updated using the client AC instance
2020-10-27 01:44:18 DEBUG (MainThread) [custom_components.electrasmart.climate] value of hvac_mode property: cool (derived from COOL)

appreciate your help...

**Comment by yonatanp** [comment]
Nice find about the "off" mode! I will make this the default behavior for
models of this kind.


As for the second part, I see that all the logs are from the exact same
second, and from two parallel threads. Could it be that the log shows the
command being sent a few seconds later? There should be either a log of the
post or a log of error, once we see that the request has been logged. Could
you check the logs from the next few minutes and see if there's anything
relevant coming from (SyncWorker_29)?

**Comment by odedgil** [comment]
Ok, I think I found the problem with the temperature  :)
you are sending "22.0" instead of "22", my AC doesn't accept that.
"SPT": "24" works while "SPT": "24.0" does not.

**Comment by yonatanp** [comment]
It's definitely surprising! I guess the HA speaks in floats. Nice catch,
I'll fix this too.

**Comment by GuyKh** [comment]
Hey @yonatanp and @odedgil - Just like you, I cant turn my AC on or off.
Even when using what you described - Turning on or off the AC, changing temperature etcetc.

Can you post a CURL command to send the command to the AC?
I'm always getting `403` when trying to send the command (even when coppying the command from the logs.

I'm using Electra A15

**Comment by odedgil** [comment]
I'm using Postman to sent http post commands to the AC and now it is working fine, I can send commands to control all the AC functionality, once the last changes will be committed by yonatan to the plugin it should work as well.
i'm using Electra Magic 370

Did you manage to get the token and id of your AC unit?
if so, try to send the following post request and see if it is working for you:
-------------------------------------------
POST /mobile/mobilecommand HTTP/1.1
Host: app.ecpiot.co.il
Content-Type: application/json

{cmd: 'VALIDATE_TOKEN','data': {'imei': 'your imei','os': 'android',    'osver': 'M4B30Z','token': 'your token'}, 'id': your id, 'pvdid': 1, 'sid': ""}
--------------------------------------------

you should get a response like:
{"id":9283,"status":0,"desc":null,"data":{"sid":"8d5b4f9232d04c6aa96f07cwqeac3339","res":0,"res_desc":null}}

**Comment by GuyKh** [comment]
@odedgil can you share your call in curl or something?

![image](https://user-images.githubusercontent.com/3136012/97298814-ac32cb80-185c-11eb-8534-d199347afc98.png)
(there's a `code` button there - then select `curl`)

I'm still not able to make the call

**Comment by odedgil** [comment]
Sure :)

curl --location --request POST 'https://app.ecpiot.co.il/mobile/mobilecommand' \
--header 'Content-Type: application/json' \
--data-raw '{cmd: '\''VALIDATE_TOKEN'\'','\''data'\'': {'\''imei'\'': '\''532587326873'\'','\''os'\'': '\''android'\'',    '\''osver'\'': '\''M4B30Z'\'','\''token'\'': '\''3812039821093820983'\''}, '\''id'\'': 2233, '\''pvdid'\'': 1, '\''sid'\'': ""}'

**Comment by GuyKh** [comment]
Awesome! Thanks

**Comment by GuyKh** [comment]
I have a similar problem - as it turns out:

```
2020-10-28 10:49:32 DEBUG (SyncWorker_40) [custom_components.electrasmart.climate] setting new temperature to 25.0
....
....
2020-10-28 10:49:32 DEBUG (SyncWorker_40) [electrasmart.client] Posting request
id: 1370
url: https://app.ecpiot.co.il/mobile/mobilecommand
headers: {'user-agent': 'Electra Client'}
post json data:
{'cmd': 'SEND_COMMAND',
 'data': {'commandJson': '{"OPER": {"MSGTYPE": "OPER", "IDU_PN": "", '
                         '"AC_MODE": "COOL", "FANSPD": "LOW", "SPT": "25.0", '
                         '"TIMER": "OFF", "HSWING": "OFF", "VSWING": "OFF", '
                         '"TURN_ON_OFF": "ON", "SLEEP": "OFF", "SHABAT": '
                         '"OFF", "CLEAR_FILT": "OFF", "OP_VAL_ERR": "OK", '
                         '"TURBO": "OFF", "IFEEL": "OFF"}}',
          'id': '123123'},
 'id': 1370,
 'pvdid': 1,
 'sid': 'xyzxyzxyz'}
2020-10-28 10:49:33 DEBUG (SyncWorker_40) [electrasmart.client] Response received (id=1370):
{'data': {'res': 0, 'res_desc': None}, 'desc': None, 'id': 1370, 'status': 0}
```


But when changing `25.0` to `25` (manually) - it works.
So I guess this should be configurable

**Comment by yonatanp** [comment]
@odedgil and @GuyKh , can you confirm that the newly pushed fixes indeed take care of this issue?
Both the first part (unable to turn off) and the second part (unable to set temperature).
Once confirmed, we can close the issue.

**Comment by GuyKh** [comment]
@yonatanp can turn off but not change the temp.
Will Investigate further next week...

**Comment by odedgil** [comment]
this is working great now.
Thank you so much!
