### ISSUE TITLE
AC stay UNAVAILABLE after wifi connection is restored

### ISSUE THREAD

**Issue by adizag** [yonatanp/electrasmart-custom-component#9]
If HA is loaded while the ac's wifi connection was not established, it shows the entity as unavailable, even if the connection was restored afterwards (and verified using the electrasmart app).

HA restart is required to gain controll of the entity again.

Tnx again for your gr8 work!!!!!

**Comment by yonatanp** [comment]
Part of #13 , closing this one as well.
